# Generated by Django 5.0.4 on 2024-04-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkara', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='technique',
            name='type',
            field=models.CharField(choices=[('uke', 'Blocage'), ('zuki', 'technique de poing'), ('geri', 'technique de jambe'), ('dachi', 'position')], default='uke', max_length=100),
        ),
    ]
