# Generated by Django 5.0.4 on 2024-05-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkara', '0002_technique_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='technique',
            name='type',
            field=models.CharField(choices=[('Blocage', 'Blocage'), ('Technique de poing', 'Technique de poing'), ('Technique de jambe', 'Technique de jambe'), ('Position', 'Position')], default='uke', max_length=100),
        ),
    ]
