# Generated by Django 5.0.4 on 2024-05-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkara', '0003_type_alter_technique_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='type',
            old_name='nom',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='technique',
            name='type',
            field=models.CharField(choices=[('Blocage', 'Blocage'), ('Technique de poing', 'Technique de poing'), ('Technique de jambe', 'Technique de jambe'), ('Position', 'Position')], default='NONE', max_length=100),
        ),
    ]
